// Copyright 2020 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.google.cloud.healthcare.etl.model.streaming;

import java.io.Serializable;
import java.time.Instant;

/** Message represents a message ready to be transformed. */
public interface Message extends Comparable<Message>, Serializable {

  /**
   * getSendTime returns the time when this message was generated by the sending application.
   */
  Instant getSendTime();

  /**
   * @return the message body.
   */
  String getBody();

  /**
   * compareTo ensures {@link Message} is comparable. Classes that need customized ordering can
   * override this method.
   */
  default int compareTo(Message m) {
    // Compare the instants explicitly.
    return getSendTime().compareTo(m.getSendTime());
  }
}
